# -*- coding: utf-8 -*-
"""GBC_DX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QvbnC_kRcU6qBH6jfBNrkTJFgynTU3iB
"""

def gbc_circuit(phi, epsilon, duration, amplitude):
    """
    Implements the MS gate with Generator-Based Compensation (GBC).

    Args:
        phi: Entangling angle for the MS gate.
        epsilon: Error coefficient for asymmetric noise.
        duration: Gate time.
        amplitude: Maximum amplitude of the waveform.

    Returns:
        QuantumCircuit: A compensated MS gate circuit.
    """
    qc = QuantumCircuit(2)

    # First MS gate
    qc.append(RXXGate(phi), [0, 1])

    # Compensation step
    # Double the asymmetric error term (equivalent to doubling duration)
    qc.rx(np.pi, 0)  # Apply correction in X basis
    qc.rx(np.pi, 1)
    qc.append(RXXGate(-phi), [0, 1])  # Apply inverted gate

    # Apply MS gate again
    qc.rx(np.pi, 0)
    qc.rx(np.pi, 1)
    qc.append(RXXGate(phi), [0, 1])

    return qc