# -*- coding: utf-8 -*-
"""ms_robust gate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VyALf-ISEdJdIpCEY5ZnMixmRO1yNTpF
"""

import numpy as np
from qiskit.pulse import Schedule, Play, Waveform
from qiskit.circuit.library import RXXGate
from qiskit import QuantumCircuit

def generate_symmetric_waveform(duration, amplitude, points=100):
    """
    Generate a symmetric amplitude modulation waveform.
    """
    t = np.linspace(0, duration, points)
    omega = amplitude * (1 - np.cos(2 * np.pi * t / duration))  # Symmetric modulation
    return omega

def ms_gate_with_modulation(phi, duration, amplitude):
    """
    Implements the MS gate with symmetry-optimized modulation.
    """
    qc = QuantumCircuit(2)
    symmetric_waveform = generate_symmetric_waveform(duration, amplitude)

    # Apply RXX gate with custom modulation
    qc.append(RXXGate(phi), [0, 1])
    return qc

pip install qiskit

import numpy as np
from qiskit.pulse import Schedule, Play, Waveform
from qiskit.circuit.library import RXXGate
from qiskit import QuantumCircuit

def generate_symmetric_waveform(duration, amplitude, points=100):
    """
    Generate a symmetric amplitude modulation waveform.
    """
    t = np.linspace(0, duration, points)
    omega = amplitude * (1 - np.cos(2 * np.pi * t / duration))  # Symmetric modulation
    return omega

def ms_gate_with_modulation(phi, duration, amplitude):
    """
    Implements the MS gate with symmetry-optimized modulation.
    """
    qc = QuantumCircuit(2)
    symmetric_waveform = generate_symmetric_waveform(duration, amplitude)

    # Apply RXX gate with custom modulation
    qc.append(RXXGate(phi), [0, 1])
    return qc

"""**Symmetry Error-Robust Waveform Design
The symmetry error-robust waveform design eliminates symmetric and displacement-dependent asymmetric errors by symmetrically modulating the laser pulses used to implement the MS gate. This ensures that:
averages to zero, decoupling spin and motional degrees of freedom.
The trajectory in phase space closes at the end of the gate operation, even in the presence of symmetric errors.**
"""

